# Generated by Django 6.0.3 on 2026-03-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RealisePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactivity_days', models.PositiveIntegerField(default=30)),
                ('grace_days', models.PositiveIntegerField(default=7)),
                ('reminder_schedule_json', models.JSONField(blank=True, default=dict)),
                ('auto_release_enabled', models.BooleanField(default=True)),
                ('require_guardians_confirmation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='release_policy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
